#!/usr/bin/env bash
# =============================================================================
#  run_analysis.sh — GROMACS trajectory analysis for all 9 complexes
# =============================================================================
#  Usage : ./run_analysis.sh
#  Expects: ./runs/<stem>/md_center.xtc + md.tpr + index.ndx  (from run_production.sh)
#  Outputs: ./runs/<stem>/analysis/*.xvg  +  ./plots/  (from analyze.py)
#
#  Analyses: RMSD, RMSF (Cα), Rg, H-bonds, Min-distance, Contacts
#  Charts  : generated by analyze.py — individual + overlaid, 300 DPI PNG
# =============================================================================
set -euo pipefail

GMX="gmx_mpi"

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${CYAN}[ANA] ${NC}  $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $*" >&2; }
ok()   { echo -e "${GREEN}[ OK ]${NC}  $*"; }
die()  { echo -e "${RED}[FAIL]${NC}  $*" >&2; exit 1; }
sep()  { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════════════${NC}"; }

command -v "${GMX}" &>/dev/null || die "${GMX} not found — activate your micromamba env."
command -v python3  &>/dev/null || die "python3 not found."

# ── Collect completed production runs ─────────────────────────────────────────
mapfile -t SYSTEMS < <(find ./runs -maxdepth 2 -name "md.tpr" | sed 's|/md.tpr||' | sort)
[[ "${#SYSTEMS[@]}" -eq 0 ]] && die "No production MD found (md.tpr) in ./runs/\nRun ./run_production.sh first."

log "Found ${#SYSTEMS[@]} system(s) with completed production MD:"
for S in "${SYSTEMS[@]}"; do
    HAS_XTC=""; [[ -f "$S/md_center.xtc" ]] && HAS_XTC="(centred traj OK)"
    log "  $S  $HAS_XTC"
done
echo ""
read -r -p "  Start analysis for ${#SYSTEMS[@]} system(s)? [y/N] " CONFIRM
[[ "${CONFIRM,,}" == "y" ]] || { log "Aborted."; exit 0; }

BATCH_START=$(date +%s)
declare -a PASSED=() FAILED=()

# =============================================================================
for SDIR in "${SYSTEMS[@]}"; do
    STEM="$(basename "$SDIR")"
    sep
    log "[$STEM] Analysing..."

    cd "$SDIR"
    mkdir -p analysis

    # ── Verify inputs ──────────────────────────────────────────────────────────
    if [[ ! -f "md.tpr" ]]; then
        warn "[$STEM] md.tpr not found — skipping"
        FAILED+=("$STEM"); cd - >/dev/null; continue
    fi

    TRAJ="md_center.xtc"
    if [[ ! -f "$TRAJ" ]]; then
        warn "[$STEM] md_center.xtc not found — falling back to md.xtc"
        TRAJ="md.xtc"
    fi
    if [[ ! -f "$TRAJ" ]]; then
        warn "[$STEM] No trajectory found — skipping"
        FAILED+=("$STEM"); cd - >/dev/null; continue
    fi

    HAS_NDX=false
    [[ -f "index.ndx" ]] && HAS_NDX=true

    # ── 1. RMSD — backbone vs initial structure ────────────────────────────────
    log "[$STEM] RMSD (backbone)..."
    printf "Backbone\nBackbone\n" | ${GMX} rms \
        -s md.tpr -f "$TRAJ" \
        -o analysis/rmsd_backbone.xvg \
        -tu ns 2>/dev/null
    ok "[$STEM] rmsd_backbone.xvg"

    # ── 2. RMSF — Cα per residue ───────────────────────────────────────────────
    log "[$STEM] RMSF (C-alpha)..."
    printf "C-alpha\n" | ${GMX} rmsf \
        -s md.tpr -f "$TRAJ" \
        -o analysis/rmsf_ca.xvg \
        -res 2>/dev/null
    ok "[$STEM] rmsf_ca.xvg"

    # ── 3. Radius of gyration ─────────────────────────────────────────────────
    log "[$STEM] Radius of gyration..."
    printf "Protein\n" | ${GMX} gyrate \
        -s md.tpr -f "$TRAJ" \
        -o analysis/gyrate.xvg \
        -tu ns 2>/dev/null
    ok "[$STEM] gyrate.xvg"

    # ── 4. H-bonds at interface (requires index.ndx) ──────────────────────────
    if $HAS_NDX; then
        log "[$STEM] Interface H-bonds..."
        printf "Nanobody\nTarget\n" | ${GMX} hbond \
            -s md.tpr -f "$TRAJ" \
            -n index.ndx \
            -num analysis/hbnum.xvg \
            -tu ns 2>/dev/null
        ok "[$STEM] hbnum.xvg"
    else
        warn "[$STEM] index.ndx missing — skipping H-bond analysis"
    fi

    # ── 5. Minimum distance + contact count at interface ─────────────────────
    if $HAS_NDX; then
        log "[$STEM] Interface min-distance + contacts (<0.35 nm)..."
        printf "Nanobody\nTarget\n" | ${GMX} mindist \
            -s md.tpr -f "$TRAJ" \
            -n index.ndx \
            -od analysis/mindist.xvg \
            -on analysis/contacts.xvg \
            -d 0.35 \
            -tu ns 2>/dev/null
        ok "[$STEM] mindist.xvg + contacts.xvg"
    else
        warn "[$STEM] index.ndx missing — skipping distance/contact analysis"
    fi

    # ── 6. RMSD per chain (nanobody only, target only) ────────────────────────
    if $HAS_NDX; then
        log "[$STEM] RMSD per chain..."
        printf "Nanobody\nNanobody\n" | ${GMX} rms \
            -s md.tpr -f "$TRAJ" \
            -n index.ndx \
            -o analysis/rmsd_nanobody.xvg \
            -tu ns 2>/dev/null
        printf "Target\nTarget\n" | ${GMX} rms \
            -s md.tpr -f "$TRAJ" \
            -n index.ndx \
            -o analysis/rmsd_target.xvg \
            -tu ns 2>/dev/null
        ok "[$STEM] rmsd_nanobody.xvg + rmsd_target.xvg"
    fi

    # ── 7. SASA (solvent accessible surface area) of interface ────────────────
    if $HAS_NDX; then
        log "[$STEM] SASA (complex vs individual chains)..."
        printf "Protein\n" | ${GMX} sasa \
            -s md.tpr -f "$TRAJ" \
            -n index.ndx \
            -o analysis/sasa_total.xvg \
            -tu ns 2>/dev/null || warn "[$STEM] SASA skipped (old GROMACS)"
    fi

    PASSED+=("$STEM")
    log "[$STEM] Analysis done — files in analysis/"
    cd - >/dev/null
done

# =============================================================================
sep
echo ""
log "GROMACS analysis done: ${#PASSED[@]}/${#SYSTEMS[@]} systems"
echo ""

if [[ "${#FAILED[@]}" -gt 0 ]]; then
    warn "Failed systems: ${FAILED[*]}"
fi

# ── Generate plots with analyze.py ────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANALYZE_PY="${SCRIPT_DIR}/analyze.py"

if [[ -f "$ANALYZE_PY" ]]; then
    echo ""
    log "Calling analyze.py to generate charts..."
    python3 "$ANALYZE_PY" ./runs ./plots
    PLOT_STATUS=$?
    if [[ $PLOT_STATUS -eq 0 ]]; then
        ok "All plots saved to ./plots/"
    else
        warn "analyze.py returned exit code ${PLOT_STATUS} — check output above"
    fi
else
    warn "analyze.py not found at ${ANALYZE_PY}"
fi

BATCH_END=$(date +%s)
TOTAL=$(( BATCH_END - BATCH_START ))
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║  ANALYSIS COMPLETE                                           ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
log "Wall time : $(( TOTAL/3600 ))h $(( (TOTAL%3600)/60 ))m $(( TOTAL%60 ))s"
echo ""
echo "Plots      : ./plots/"
echo "XVG files  : ./runs/<stem>/analysis/"
echo ""
echo "For MM-PBSA binding energies, run:"
echo "  ./run_mmpbsa.sh"
echo ""
